# version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 21

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - bundle install --jobs 4 --retry 2 --without development

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - type Gemfile.lock

test_script:
  - bundle exec rake spec acceptance:local

notifications:
  - provider: HipChat
    auth_token:
      secure: W9FwcoLtq+0XUqE3lM6m8zGdPdIOfHNafvdVD0qtoG0ra3C3hkseSaHR6uO8h/h2
    room: 3519749
    template: >
      {{repositoryName}}#{{buildNumber}} ({{#isPullRequest}}PR {{pullRequestId}}{{/isPullRequest}}{{^isPullRequest}}{{branch}}{{/isPullRequest}} - {{commitId}} : {{commitAuthor}}): {{status}} (<a href="{{buildUrl}}">Details</a>{{#isPullRequest}} | <a href="https://github.com/{{repositoryName}}/pull/{{pullRequestId}}">PR</a>{{/isPullRequest}})
