build: off

# ruby versions under test
platform:
  - Ruby23-x64
  - Ruby21-x64

test_script:
  - SET PATH=C:\%PLATFORM%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - bundle install --jobs 4 --retry 2 --without development
  - type Gemfile.lock
  - ruby -v
  - bundle exec rake spec

notifications:
  - provider: HipChat
    auth_token:
      secure: W9FwcoLtq+0XUqE3lM6m8zGdPdIOfHNafvdVD0qtoG0ra3C3hkseSaHR6uO8h/h2
    room: 3519749
    template: >
      {{repositoryName}}#{{buildNumber}} ({{#isPullRequest}}PR {{pullRequestId}}{{/isPullRequest}}{{^isPullRequest}}{{branch}}{{/isPullRequest}} - {{commitId}} : {{commitAuthor}}): {{status}} (<a href="{{buildUrl}}">Details</a>{{#isPullRequest}} | <a href="https://github.com/{{repositoryName}}/pull/{{pullRequestId}}">PR</a>{{/isPullRequest}})
